#apiVersion: apps/v1
apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: c1
  labels:
    comp: c1

spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      comp: c1
  template:
    metadata:
      labels:
        comp: c1
    spec:
      containers:
      - name: main
        image: opsani/co-http:latest
        args: [busy=1300]      # 1050
        resources:
          limits:   # testA
            # testB
            cpu: '0.44'   # testC
            memory: 304.4Mi   # testD
        ports:   # testE
          - containerPort: 8080
      nodeSelector:
        oco: '1'
