#apiVersion: apps/v1
apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: c2
  labels:
    comp: c2

spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      comp: c2
  template:
    metadata:
      labels:
        comp: c2
    spec:
      containers:
      - name: main
        image: opsani/co-http:latest
        args: [busy=150&call=c1]      # 150 work units
        resources:
          limits:
            cpu: '1.2'
            memory: 412.0Mi
        ports:
        - containerPort: 8080
      nodeSelector:
        oco: '2'
